husky에 test coverage 추가

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx lint-staged
+yarn lint-staged
+
+# yarn test:cov
+# sleep 60
+# coverage_percentage=$(node -e "console.log(require('../coverage/coverage-final.json').total.lines.pct)")
+
+# if [ "$coverage_percentage" -lt 80 ]; then
+#   echo "Error: Test coverage is below 80% ($coverage_percentage%). Please increase test coverage before committing."
+#   exit 1
+# fi
